version: '3'
services:
  rabbitmq:
    container_name: rabbitmq-thoth
    image: rabbitmq:3.6
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672" 
      - "15672:15672" 

  mongo:
    container_name: mongo-thoth
    image: mongo:3.2
    restart: always 
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db

  postgres: 
    container_name: postgres-thoth
    image: postgres:10
    restart: always 
    ports: 
      - "5432:5432"

  web:
    container_name: web-thoth
    env_file: web/web-variables.env
    restart: always
    build: ./web
    command: python /web/manage.py migrate --noinput
    command: bash -c "gunicorn config.wsgi:application -w 2 -b :8000"
    ports:
      - "8000:8000"
    volumes:
      - ./web:/web
    depends_on: 
      - postgres 

  celery:
    container_name: celery-thoth
    env_file: web/web-variables.env
    restart: always
    build: ./web
    command: bash -c "celery worker -c 2 --loglevel=info -A config -Q default -n default@%h" 
    volumes:
      - ./web:/web
    links:
      - postgres
      - mongo
      - rabbitmq
    depends_on:
      - rabbitmq

